// Add the official Dapr Helm chart.
helm repo add dapr https://dapr.github.io/helm-charts/
helm repo update
# See which chart versions are available
helm search repo dapr --devel --versions


helm upgrade --install dapr dapr/dapr \
--version=1.9.5 \
--namespace dapr-system \
--create-namespace \
--wait

kubectl get pods --namespace dapr-system

helm uninstall dapr --namespace dapr-system

dapr run --app-id DaprCounter dotnet run